Feature/user email validation
astronomer/houston-api pull request #437
Opened 2020-08-25 22:07 UTC by adam2k

## Description

Resolve invalid email addresses being used when adding a user to a workspace.  

## 🎟 Issue(s)

Resolves astronomer/issues/1630

## 🧪 Functional Testing

1. Start Houston API
2. Using astro cli (this is version 0.19.0, but 0.18.0 or other previous versions should also work) run the following commands:

```
$ astro auth login localhost
$ astro workspace user add Testing
Your Astro CLI Version (0.19.0) is ahead of the server version (0.15.1).
Consider downgrading your Astro CLI to match. See https://www.astronomer.io/docs/cli-quickstart for more information.
Error: Invalid email address. Please check the address and try again
```

Note the Houston Logs: 
```
2020-08-25T18:03:38 ERROR Invalid email address. Please check the address and try again
```

## 📸 Screenshots

N/A (included the astro cli logs)

## 📋 Checklist

- [ ] Rebased from the main (or release if patching) branch (before testing)
- [ ] Ran `yarn lint && yarn test` before taking out of draft
- [ ] Added/updated applicable tests
- [ ] Tested against [Astro-UI](https://github.com/astronomer/astro-ui/) and [Astro-CLI](https://github.com/astronomer/astro-cli/) clients.
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/astro-docs/)

2020-08-27 13:10 UTC, andriisoldatenko commented on src/lib/users/index.js
> +  const pattern = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
can you please add source of regular expression? does it support unicode?

2020-08-27 13:11 UTC, andriisoldatenko commented on src/lib/users/index.js
> +  const pattern = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
can you please move it to constants.js?

2020-08-27 13:14 UTC, andriisoldatenko requested changes

2020-08-27 13:14 UTC, andriisoldatenko commented on src/lib/users/index.js
> +  const pattern = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
something like https://github.com/astronomer/houston-api/blob/6e75c5c44e022a724aac1e1f182fb7a8936ed08d/src/lib/constants/index.js#L58

2020-08-27 16:37 UTC, adam2k commented on src/lib/users/index.js
> +  const pattern = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
Yeah, good idea.  I can move to constants.

I found this regex here: https://emailregex.com/

2020-08-27 16:39 UTC, adam2k commented on src/lib/users/index.js
> +  const pattern = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
I'm not sure about unicode.  Do you have a list of characters that I can use for test cases to validate?  We might need to modify this regex.

2020-08-27 16:40 UTC, adam2k commented on src/lib/users/index.js
> +  const pattern = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
I can use this as a starting point. https://en.wikipedia.org/wiki/List_of_Unicode_characters

2020-08-27 16:54 UTC, adam2k commented on src/lib/users/index.js
> +  const pattern = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
I found a pretty good example here.  https://jsfiddle.net/aossikine/qCLVH/3/

2020-08-27 16:55 UTC, adam2k commented on src/lib/constants/index.js
> +export const EMAIL_PATTERN = /^(?!\.)((?!.*\.{2})[a-zA-Z0-9\u0080-\u00FF\u0100-\u017F\u0180-\u024F\u0250-\u02AF\u0300-\u036F\u0370-\u03FF\u0400-\u04FF\u0500-\u052F\u0530-\u058F\u0590-\u05FF\u0600-\u0
We could either go for something involved like this or keep the validation very basic at first?

2020-08-27 22:06 UTC, adam2k commented
> Looks good to me, assuming the regex is legit

I'm debating if we should go with this approach for unicode support or do something more basic, but may allow for some invalid use cases.

2020-08-27 22:31 UTC, vishwas-astro commented
> > Looks good to me, assuming the regex is legit
> 
> I'm debating if we should go with this approach for unicode support or do something more basic, but may allow for some invalid use cases.

My preference is to go with something simple that we can test.

2020-08-28 16:46 UTC, andriisoldatenko commented on src/lib/constants/index.js
> +export const EMAIL_PATTERN = /^(?!\.)((?!.*\.{2})[a-zA-Z0-9\u0080-\u00FF\u0100-\u017F\u0180-\u024F\u0250-\u02AF\u0300-\u036F\u0370-\u03FF\u0400-\u04FF\u0500-\u052F\u0530-\u058F\u0590-\u05FF\u0600-\u0
@adam2k wha't the source of RegExpression?

2020-09-01 13:24 UTC, adam2k commented on src/lib/constants/index.js
> +export const EMAIL_PATTERN = /^\S+@\S{4,}$/i;
@samblackk @ryanahamilton FYI for email validation.  I don't think this should impact Astro UI, but wanted to point this out just in case.

2020-09-01 13:31 UTC, ryanahamilton commented on src/lib/constants/index.js
> +export const EMAIL_PATTERN = /^\S+@\S{4,}$/i;
Thanks for the heads-up. I don't believe we're validating any patterns on the client beyond the browser-enforced patterns for email input types, so all should be good.

2020-09-01 15:50 UTC, adam2k commented on src/lib/constants/index.js
> +export const EMAIL_PATTERN = /^\S+@\S{4,}$/i;
Thanks!  I posted a screenshot in the PR comments, so I think that error toast should work.  Just giving a heads up if you want to make any changes.

2020-09-01 15:51 UTC, adam2k commented on src/lib/constants/index.js
> +export const EMAIL_PATTERN = /^(?!\.)((?!.*\.{2})[a-zA-Z0-9\u0080-\u00FF\u0100-\u017F\u0180-\u024F\u0250-\u02AF\u0300-\u036F\u0370-\u03FF\u0400-\u04FF\u0500-\u052F\u0530-\u058F\u0590-\u05FF\u0600-\u0
I changed it to something more simple, but this outdated regex came from this jsFiddle: 

> I found a pretty good example here. https://jsfiddle.net/aossikine/qCLVH/3/

2020-09-10 15:14 UTC, andriisoldatenko commented
@adam2k we need to resolve conflicts

2020-09-14 13:25 UTC, adam2k commented
> @adam2k we need to resolve conflicts

@andriisoldatenko resolved all conflicts.

2020-09-14 14:56 UTC, adam2k commented
I'm switching this back to draft, so this does **not** get merged until after the Primsa 2 deployment goes out.

2020-09-28 12:04 UTC, andriisoldatenko commented on src/lib/errors/errors.js
> +    super("Invalid email address. Please check the address and try again");
```suggestion
    super("Invalid email address. Please use valid email address");
```
wdyt ?
cc @paolaperaza

2020-09-29 13:56 UTC, andriisoldatenko approved these changes

2020-09-29 14:22 UTC, merged