1812 user invites roles
astronomer/houston-api pull request #482
Opened 2020-10-01 23:08 UTC by kushalmalani

## Description

> Describe the purpose of this pull request.

## 🎟 Issue(s)

Resolves astronomer/issues#1812

## 🧪 Functional Testing

> List the functional testing steps to confirm this feature or fix.

## 📸 Screenshots

> Add screenshots to illustrate the validity of these changes.

## 📋 Checklist

- [ ] Rebased from the main (or release if patching) branch (before testing)
- [ ] Ran `yarn lint && yarn test` before taking out of draft
- [ ] Added/updated applicable tests
- [ ] Tested against [Astro-UI](https://github.com/astronomer/astro-ui/) and [Astro-CLI](https://github.com/astronomer/astro-cli/) clients.
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

2020-10-02 13:28 UTC, andriisoldatenko commented on src/lib/users/index.js
> +    where: { username: email, status: "pending", token }
can we use constant instead of string: "pending"?

2020-10-02 13:33 UTC, andriisoldatenko requested changes

2020-10-02 13:33 UTC, andriisoldatenko commented on src/migrations/20200921231650_copy_invites_to_users.js
> +const schema = "houston$default";
please use 
```suggestion
const schema = config.get("database.schema");
```

2020-10-02 13:36 UTC, andriisoldatenko commented on package.json
> +    "cuid": "^2.1.8",
@adam2k i think we can reuse this lib in your PR ^^.

2020-10-02 14:32 UTC, adam2k commented on package.json
> +    "cuid": "^2.1.8",
@andriisoldatenko I'm wondering if we should use this lib or roll our own?  Right now we're only using two functions (one in this PR `cuid()` and then in my PR I'm using `isCuid()`).  What do you think?  I'm thinking less potential snyk PRs to deal with if this lib ends up with any issues.

2020-10-02 14:34 UTC, adam2k commented on package.json
> +    "cuid": "^2.1.8",
nvm...this library is pretty lightweight.  I can add this into my PR too.

2020-10-02 15:07 UTC, andriisoldatenko commented
Please correct if i’m wrong just trying to understand the whole problem:

because we have https://github.com/astronomer/houston-api/blob/a9b3d9766e7d66edfc3ab74f580a0815e3279d25/prisma/schema.prisma#L103 `InviteToken` only with workspace we can’t invite users to deployments ONLY?

so instead of adding deploymentId to InviteToken we decided to add token column to User model? (edited) 

i mean similar to RoleBinding :

```model RoleBinding {
  id             String          @default(cuid()) @id
  role           Role?
  user           User?            @relation(fields: [userId], name: "RoleBindingToUser", references: [id])
  userId         String?
  serviceAccount ServiceAccount? @relation(fields: [serviceAccountId], name: "RoleBindingToServiceAccount", references: [id])
  serviceAccountId String?
  workspace      Workspace?      @relation(fields: [workspaceId], name: "RoleBindingToWorkspace", references: [id])
  workspaceId    String?
  deployment     Deployment?     @relation(fields: [deploymentId], name: "DeploymentRoleBindings", references: [id])
  deploymentId   String?
  createdAt      DateTime        @default(now())
  updatedAt      DateTime        @updatedAt
}
```
we can have workspace/or deployment reference.
cc @schnie @adam2k @ryanahamilton

2020-10-02 19:15 UTC, adam2k commented on src/lib/users/index.js
> +  if (inviteToken.length === 0) throw new InviteTokenNotFoundError();
is it possible for inviteToken to be null?  I'd recommend

```Suggestion
  if (!inviteToken || inviteToken.length === 0) throw new InviteTokenNotFoundError();
```

2020-10-02 19:48 UTC, adam2k reviewed
This is starting to look pretty good.  I have a couple of nits and some clean up comments.  I think if some of the consolidation goes in to make the code more DRY it'll make it easier to spot any potential bugs.

2020-10-02 19:48 UTC, adam2k commented on src/migrations/20200921231650_copy_invites_to_users.js
> +  await knex.transaction(async function(trx) {
Do we need a knex transaction or can we do this with a Prisma migration instead?  It'll be easier to manage if we can use Prisma only unless it won't work in this situation.

2020-10-02 19:48 UTC, adam2k commented on src/resolvers/mutation/invite-user/index.js
> +  if (emailRow.length > 0) {
Is it possible for emailRow to be null?  If so:

```Suggestion
  if (size(emailRow) > 0) {
```

2020-10-02 19:48 UTC, adam2k commented on src/resolvers/mutation/workspace-add-user/index.js
> +  const user = emailRow.length > 0 ? emailRow[0].user : null;
This could be:

```Suggestion
  const user = get(emailRow, "[0].user", null);
```

2020-10-02 19:48 UTC, adam2k commented on src/resolvers/mutation/workspace-add-user/index.js
>    const email = validateEmailAddress(emailArg);
I'm noticing that there are some `email.toLowerCase()` and other references that aren't.  I'd suggest formatting the email to lowercase somewhere up here to prevent downstream bugs with string comparisons.

2020-10-02 19:48 UTC, adam2k commented on src/resolvers/mutation/workspace-update-user-role/index.js
> +      user: { username: email }
This almost reads like a mistake, even though it's not.  I'd consider changing line 14 to something like

`const { email: username, workspaceUuid, role } = args;`

and then this line

```Suggestion
      user: { username }
```

2020-10-02 19:48 UTC, adam2k commented on src/resolvers/query/invites/index.js
> +      user: { status: "pending", ...query }
@andriisoldatenko mentioned this in an earlier comment, but can "pending" be a const?

2020-10-02 19:48 UTC, adam2k commented on src/resolvers/types/workspace/index.js
> +    };
To avoid repeating can this be converted into a lib function and used here and `src/resolvers/query/workspace-invites/index.js`?

It seems like eventually one of this blocks could be updated, but not the other.

2020-10-02 23:22 UTC, kushalmalani commented
> Please correct if i’m wrong just trying to understand the whole problem:
> 
> because we have
> 
> https://github.com/astronomer/houston-api/blob/a9b3d9766e7d66edfc3ab74f580a0815e3279d25/prisma/schema.prisma#L103
> `InviteToken` only with workspace we can’t invite users to deployments ONLY?
> 
> so instead of adding deploymentId to InviteToken we decided to add token column to User model? (edited)
> 
> i mean similar to RoleBinding :
> 
> ```
>   id             String          @default(cuid()) @id
>   role           Role?
>   user           User?            @relation(fields: [userId], name: "RoleBindingToUser", references: [id])
>   userId         String?
>   serviceAccount ServiceAccount? @relation(fields: [serviceAccountId], name: "RoleBindingToServiceAccount", references: [id])
>   serviceAccountId String?
>   workspace      Workspace?      @relation(fields: [workspaceId], name: "RoleBindingToWorkspace", references: [id])
>   workspaceId    String?
>   deployment     Deployment?     @relation(fields: [deploymentId], name: "DeploymentRoleBindings", references: [id])
>   deploymentId   String?
>   createdAt      DateTime        @default(now())
>   updatedAt      DateTime        @updatedAt
> }
> ```
> 
> we can have workspace/or deployment reference.
> cc @schnie @adam2k @ryanahamilton

@andriisoldatenko Yes, thats accurate. The solution to create/delete many records in InviteTokens table, everytime we add a user to workspace seems inefficient and there is a redundancy in data we were storied which would have been optimized using User and RoleBindings table

2020-10-02 23:40 UTC, kushalmalani commented on src/lib/users/index.js
> +  if (inviteToken.length === 0) throw new InviteTokenNotFoundError();
It would be not, since findMany returns a list....so it would be an empty array at best. But it would hurt to use isEmpty, just to be on the safe side. Will update.

2020-10-05 00:04 UTC, kushalmalani commented on src/migrations/20200921231650_copy_invites_to_users.js
> +  await knex.transaction(async function(trx) {
Dont we use prisma only to manage our schema? We use knex for migration of data in 0.20, so i wanted to maintain same behavior.

@andriisoldatenko Thoughts?

2020-10-05 00:13 UTC, kushalmalani commented on src/resolvers/mutation/invite-user/index.js
> +  if (emailRow.length > 0) {
Again, no...but we can add it to be on safer side

2020-10-05 00:24 UTC, kushalmalani commented on src/resolvers/mutation/workspace-add-user/index.js
>    const email = validateEmailAddress(emailArg);
validateEmailAddress already does that. I forgot to remove the lowercase references after merging with main

2020-10-05 00:50 UTC, kushalmalani commented on src/resolvers/types/workspace/index.js
> +    };
Yeah, that makes sense. Updating that.

2020-10-05 16:17 UTC, andriisoldatenko commented on prisma/migrations/migrate.lock
> +20200922172359-add-new-columns-user-table
wrong order cc @adam2k

2020-10-05 16:22 UTC, schnie commented on src/migrations/20200921231650_copy_invites_to_users.js
> +  await knex.transaction(async function(trx) {
My understanding was that the prisma migrations only do schema related changes. The reason we added `knex` migrations back in the day, was to give us a way to move actual data in migrations. Can prisma migrations do that now?

But within the migrations themselves, we might be able to use the prima client instead of the raw SQL. What do you all think?

2020-10-05 16:23 UTC, andriisoldatenko commented on src/migrations/20200921231650_copy_invites_to_users.js
> +  await knex.transaction(async function(trx) {
correct, i'm not sure that you can do it using prisma migrations.
@adam2k AFAIK prisma migrate supports only data modeling! https://www.prisma.io/docs/understand-prisma/data-modeling

2020-10-05 16:37 UTC, adam2k commented on src/migrations/20200921231650_copy_invites_to_users.js
> +  await knex.transaction(async function(trx) {
Ah okay, I thought the Prisma migrations could handle more use cases.  Using `knex` works for me then.  We can revisit when Prisma migrate comes out of the experimental phase.

2020-10-06 01:14 UTC, schnie commented on src/migrations/20200921231650_copy_invites_to_users.js
> +  await knex.transaction(async function(trx) {
Should we use knex and raw SQL here or use the prisma client like we do in the rest of the app?

Standardizing seems like a good thing, but I could be missing something. What do y'all think? Could be nitpicking

2020-10-06 01:15 UTC, adam2k approved these changes
Looks good to me! 🎉 🚀 🥳

2020-10-06 01:16 UTC, schnie commented on src/migrations/20200921231650_copy_invites_to_users.js
> +  await knex.transaction(async function(trx) {
Should we use knex and raw SQL here or use the prisma client like we do in the rest of the app?

Standardizing seems like a good thing, but I could be missing something. What do y'all think? Could be nitpicking

2020-10-06 13:14 UTC, andriisoldatenko commented on src/generated/schema.graphql
> +  deleteInviteToken(inviteUuid: Uuid, workspaceUuid: Uuid): Invite
do we need to update astro-ui?
https://github.com/astronomer/astro-ui/blob/148732c556abf6384f2f8992610d8b49f20e137a/src/api/mutate/workspaceInviteDelete.js#L8
cc @samblackk @ryanahamilton

2020-10-06 14:25 UTC, andriisoldatenko commented on src/generated/schema.graphql
> +  deleteInviteToken(inviteUuid: Uuid, workspaceUuid: Uuid): Invite
nvm it fixed in https://github.com/astronomer/astro-ui/blob/f6d338e148273a0b94ea4d3cad2af10d622e0372/src/api/mutate/workspaceInviteDelete.js#L9

2020-10-06 14:32 UTC, andriisoldatenko approved these changes

2020-10-06 14:33 UTC, andriisoldatenko commented
practically LGTM.

2020-10-06 15:16 UTC, kushalmalani commented on src/migrations/20200921231650_copy_invites_to_users.js
> +  await knex.transaction(async function(trx) {
@schnie I think its worth exploring. Maybe we can file a separate ticket and look into it and not block this going into release.

2020-10-06 15:19 UTC, schnie commented on src/lib/invites/index.js
> +export function inviteResponseConformation(invites) {
```suggestion
export function inviteResponseConfirmation(invites) {
```

2020-10-06 15:23 UTC, schnie approved these changes

2020-10-06 15:40 UTC, merged