1811 - Add KEDA Update Mutation
astronomer/houston-api pull request #488
Opened 2020-10-05 20:08 UTC by samblackk

## Description

Add's a mutation that allows user to enable or disable the KEDA worker. 

## 🎟 Issue(s)

Resolves https://github.com/astronomer/issues/issues/1811

## 🧪 Functional Testing

Can test in the playground: 
```
mutation updateDeploymentKedaConfig(
  $deploymentUuid: Uuid!
  $state: Boolean!
) {
  updateDeploymentKedaConfig(
    deploymentUuid: $deploymentUuid
    state: $state
  ) {
    id
    config
  }
}
```

**Variables:**
`deploymentUuid` = deployment.id
`state` = true/false boolean

## 📸 Screenshots

> Add screenshots to illustrate the validity of these changes.

## 📋 Checklist

- [x] Rebased from the main (or release if patching) branch (before testing)
- [x] Ran `yarn lint && yarn test` before taking out of draft
- [x] Added/updated applicable tests
- [x] Tested against [Astro-UI](https://github.com/astronomer/astro-ui/) and [Astro-CLI](https://github.com/astronomer/astro-cli/) clients.
- [x] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [x] Updated any related [documentation](https://github.com/astronomer/docs/)

2020-10-05 20:20 UTC, adam2k commented
This works well with a proper ID.  But it seems like an invalid ID is not being error handled correctly.

![Screen Shot 2020-10-05 at 4 20 06 PM](https://user-images.githubusercontent.com/749118/95127840-a860cd00-0726-11eb-859e-6b2ab18beed8.png)

2020-10-05 20:24 UTC, andriisoldatenko approved these changes

2020-10-05 20:25 UTC, adam2k commented on src/resolvers/mutation/update-deployment-keda-config/index.js
> +  return await ctx.prisma.deployment.update({
Can this error handle for invalid `deploymentUuid`?

2020-10-05 20:26 UTC, andriisoldatenko commented on src/resolvers/mutation/update-deployment-keda-config/index.js
> +  return await ctx.prisma.deployment.update({
yeah we can query and raise not found before updating.

2020-10-05 20:26 UTC, andriisoldatenko commented on src/resolvers/mutation/update-deployment-keda-config/index.js
> +  return await ctx.prisma.deployment.update({
@schnie wdyt?

2020-10-05 20:27 UTC, andriisoldatenko commented on src/resolvers/mutation/update-deployment-keda-config/index.js
> +  return await ctx.prisma.deployment.update({
but problem that we have similar code here too https://github.com/astronomer/houston-api/blob/3300c9e743e1b340e80ccde2aa7b11568caf0124/src/resolvers/mutation/update-workspace/index.js#L14
looks like @samblackk tries to be consistent.

2020-10-05 20:27 UTC, adam2k commented on src/resolvers/mutation/update-deployment-keda-config/index.js
> +  return await ctx.prisma.deployment.update({
I think we should do something there otherwise we're going to have potential for a bunch of errors in the logs from what I pasted in the comment above.

2020-10-05 20:27 UTC, schnie commented on src/resolvers/mutation/update-deployment-keda-config/index.js
> +  return await ctx.prisma.deployment.update({
Yea makes sense. Should we do that everywhere? Should it be a decorator or something reusable?

2020-10-05 20:29 UTC, adam2k commented on src/resolvers/mutation/update-deployment-keda-config/index.js
> +  return await ctx.prisma.deployment.update({
yeah, I can make a ticket for that other one that can error out too.  I bet there are others that we missed as well.

2020-10-05 20:34 UTC, andriisoldatenko commented on src/resolvers/mutation/update-deployment-keda-config/index.js
> +  return await ctx.prisma.deployment.update({
so we can just improve this PR, and create separate PR for other places IMO

2020-10-05 20:48 UTC, adam2k commented on src/resolvers/mutation/update-deployment-keda-config/index.js
> +            endabled: state
Realized there is a typo here:

```Suggestion
            enabled: state
```

2020-10-05 20:49 UTC, adam2k requested changes
I added a suggestion to fix a typo.  We're also looking into a higher order function or something that we can wrap the update in to prevent the cryptic error messages.

2020-10-05 20:55 UTC, samblackk commented
@adam2k @andriisoldatenko Improvements applied

2020-10-05 20:57 UTC, dimberman commented
Was gonna comment about "endabled" but looks like that was fixed!

2020-10-05 20:59 UTC, adam2k approved these changes
Did some functional testing with the GraphQL playground. This LGTM!  🎉

2020-10-05 21:14 UTC, samblackk commented
Wait - hold on merging - bug found: this just replaces the entire `JSON` blob instead of updating the portion in `data`. 
I need to rework this.

2020-10-05 21:32 UTC, samblackk commented
Ok. Fixed. Phew.

2020-10-05 21:36 UTC, adam2k commented
I added an issue to keep track of the conversation about `decorators` and/or `high order` functions to wrap the mutations in error handlers somehow here: https://github.com/astronomer/issues/issues/1892

2020-10-06 01:03 UTC, samblackk commented
This needs to get into `0.21` :)

2020-10-06 02:32 UTC, schnie approved these changes
LGTM

2020-10-07 20:29 UTC, merged

2020-10-12 15:33 UTC, schnie commented
@shabx @dimberman @vishwas-astro do we want to get this into the next patch for EA?