Fix service account downgrades workspace admin to viewer
astronomer/houston-api pull request #500
Opened 2020-10-10 00:09 UTC by kushalmalani

## Description

> Describe the purpose of this pull request.
Fixing mutation to create rolebinding without assigned UserId to a new deployment service account, since this is causing the workspace admin (non system admin) user to downgrade and have view access under deployment level.

## 🎟 Issue(s)

Resolves astronomer/issues#1901

## 🧪 Functional Testing

> List the functional testing steps to confirm this feature or fix.

## 📸 Screenshots

> Add screenshots to illustrate the validity of these changes.

## 📋 Checklist

- [ ] Rebased from the main (or release if patching) branch (before testing)
- [ ] Ran `yarn lint && yarn test` before taking out of draft
- [ ] Added/updated applicable tests
- [ ] Tested against [Astro-UI](https://github.com/astronomer/astro-ui/) and [Astro-CLI](https://github.com/astronomer/astro-cli/) clients.
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

2020-10-11 01:29 UTC, vishwas-astro commented on src/resolvers/mutation/create-deployment-service-account/index.js
> +          deployment: { connect: { id: deploymentUuid } }
@kushalmalani trying to understand the syntax here. Is this basically creating a record without userId but only serviceAccountID and deploymentUUID?

Also, any chance we can add a test.

2020-10-12 00:21 UTC, kushalmalani commented on src/resolvers/mutation/create-deployment-service-account/index.js
> +          deployment: { connect: { id: deploymentUuid } }
@vishwas-astro Yes, creating a rolebinding with userId is overrding the user deployment role. We already have a test covering this scenario. We didnt have one with userId.

is there a specific scenario you want a test on?

2020-10-12 01:11 UTC, vishwas-astro commented on src/resolvers/mutation/create-deployment-service-account/index.js
> +          deployment: { connect: { id: deploymentUuid } }
Basically, after the operation,  ensure that there are 2 role bindings, one for user ID/depl Id and another for service acct Id/depl Id.

2020-10-12 06:08 UTC, andriisoldatenko requested changes
Please add practical and unit tests to make sure there is no regression.

2020-10-12 07:14 UTC, andriisoldatenko commented on src/resolvers/mutation/create-deployment-service-account/index.js
> +          deployment: { connect: { id: deploymentUuid } }
@kushalmalani try to add something like:
```
expectx(expect).toHaveBeenCalledWith({without user})
```
also try to create new deployment service account/old service account and check if you can do astro deploy/or basic astro cli operations.

2020-10-12 12:54 UTC, andriisoldatenko commented
@kushalmalani i still don't understand the change... i created SA before and after your change:
```
postgres=# select "deploymentId", "userId" from "RoleBinding" where "deploymentId" = 'ckg6ioeng03270jxtbrht0glw';
       deploymentId        |          userId
---------------------------+---------------------------
 ckg6ioeng03270jxtbrht0glw |
 ckg6ioeng03270jxtbrht0glw | ckg6io5b500070jxtzhhki9u9
(2 rows)
```

2020-10-12 12:59 UTC, andriisoldatenko commented
@kushalmalani can you please demonstrate which query returns less data before and after you change?

2020-10-12 14:06 UTC, andriisoldatenko commented
@kushalmalani make sense!

it's just typo in 0.20:
`it diff release-0.20 release-0.18 -- src/resolvers/mutation/create-deployment-service-account/index.js`

```diff
diff --git src/resolvers/mutation/create-deployment-service-account/index.js src/resolvers/mutation/create-deployment-service-account/index.js
index 60c75da4..bab84020 100644
--- src/resolvers/mutation/create-deployment-service-account/index.js
+++ src/resolvers/mutation/create-deployment-service-account/index.js
@@ -1,3 +1,6 @@
+import fragment from "./fragment";
+import validateExistence from "service-accounts/existence";
+import { addFragmentToInfo } from "graphql-binding";
 import crypto from "crypto";
 
 /*
@@ -10,11 +13,15 @@ import crypto from "crypto";
 export default async function createDeploymentServiceAccount(
   parent,
   args,
-  ctx
+  ctx,
+  info
 ) {
   // Pull out some variables.
   const { label, category, deploymentUuid, role } = args;
 
+  // Validate if service account label exists or not
+  await validateExistence({ label, deploymentUuid });
+
   // Create the base mutation.
   const mutation = {
     data: {
@@ -25,13 +32,17 @@ export default async function createDeploymentServiceAccount(
       roleBinding: {
         create: {
           role,
-          deployment: { connect: { id: deploymentUuid } },
-          user: { connect: { id: ctx.user.id } }
+          deployment: {
+            connect: { id: deploymentUuid }
+          }
         }
       }
     }
   };
 
   // Run the mutation.
-  return ctx.prisma.serviceAccount.create(mutation);
+  return ctx.db.mutation.createServiceAccount(
+    mutation,
+    addFragmentToInfo(info, fragment)
+  );
 }

```

2020-10-12 14:07 UTC, andriisoldatenko approved these changes

2020-10-12 14:51 UTC, adam2k commented on src/resolvers/mutation/create-deployment-service-account/index.unit.test.js
> +    expect(expected.user).toBeFalsy();
@kushalmalani @andriisoldatenko let me know if this is the correct test for this mutation.  This should never return a user object, correct?

2020-10-12 14:52 UTC, adam2k commented on src/resolvers/mutation/create-deployment-service-account/index.unit.test.js
> +    expect(actual.user).toBeFalsy();
@kushalmalani @andriisoldatenko let me know if this is correct.  There shouldn't be a user object for any service account, correct?

2020-10-12 15:04 UTC, kushalmalani commented on src/resolvers/mutation/create-deployment-service-account/index.unit.test.js
> +    expect(actual.user).toBeFalsy();
Yeah, this looks ok

2020-10-12 15:05 UTC, adam2k commented on src/resolvers/mutation/create-deployment-service-account/index.unit.test.js
> +    expect(actual.user).toBeFalsy();
If you want to we could also validate that all the values come back correctly that are mocked out in the create const, but that might not be necessary.

2020-10-12 15:07 UTC, adam2k approved these changes
Looks good to me! 🎉

2020-10-12 15:08 UTC, kushalmalani commented on src/resolvers/mutation/create-deployment-service-account/index.unit.test.js
> +    expect(actual.user).toBeFalsy();
its a mock right...its going to return whatever we send, regardless.

2020-10-12 15:09 UTC, merged