deployment update user role
astronomer/houston-api pull request #522
Opened 2020-10-21 06:45 UTC by kushalmalani

## Description

> Describe the purpose of this pull request.
deployment update user role mutation

## 🎟 Issue(s)

Resolves astronomer/issues#1762

## 🧪 Functional Testing

> List the functional testing steps to confirm this feature or fix.

## 📸 Screenshots

> Add screenshots to illustrate the validity of these changes.

## 📋 Checklist

- [ ] Rebased from the main (or release if patching) branch (before testing)
- [ ] Ran `yarn lint && yarn test` before taking out of draft
- [ ] Added/updated applicable tests
- [ ] Tested against [Astro-UI](https://github.com/astronomer/astro-ui/) and [Astro-CLI](https://github.com/astronomer/astro-cli/) clients.
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

2020-10-22 13:53 UTC, adam2k requested changes
I have some small nits, but the biggest comment is about if we should start using `Id` instead of `Uuid` because this is a new mutation.  I think it'll be confusing for now, but less for us to change in the future.

It'll require updating the `add user role` and updating `Astro CLI` and `Astro UI` if the changes are already implemented in a branch there.

2020-10-22 13:53 UTC, adam2k commented on src/generated/schema.graphql
> +  deploymentUpdateUserRole(deploymentUuid: Uuid!, email: String!, role: Role!, userUuid: Uuid): RoleBinding
For new queries did we decide to change to `deploymentId` and `userId` OR `deploymentID` and `userID` (which is my preference).

I know it'll be weird because the API requests will vary for the short term, but it's less to change in the future if we make this change now.  cc: @andriisoldatenko @schnie

2020-10-22 13:53 UTC, adam2k commented on src/resolvers/mutation/deployment-update-user-role/index.js
> +  let userId = userUuid;
We don't need this change if we change from `userUuid` to `userId` in the mutation.

2020-10-22 13:53 UTC, adam2k commented on src/resolvers/mutation/deployment-update-user-role/index.unit.test.js
> +import { schema } from "schema";
The `Uuid` suggestion would fix all the `Id` references here too.

2020-10-22 16:42 UTC, kushalmalani commented on src/resolvers/mutation/deployment-update-user-role/index.js
> +  let userId = userUuid;
Cant use it as const, since i am updating userUuid

2020-10-22 16:42 UTC, kushalmalani commented on src/resolvers/mutation/deployment-update-user-role/index.js
> +  if (isEmpty(user) || user.roleBindings.length === 0) {
I can add another check in here

2020-10-23 13:47 UTC, adam2k commented on src/resolvers/mutation/deployment-update-user-role/index.js
> +  let userId = userUuid;
I'm confused about why the `userId` is changing?  That doesn't change after the user is created, right?  Can we use this suggestion and remove line 35?

2020-10-23 15:19 UTC, kushalmalani commented on src/resolvers/mutation/deployment-update-user-role/index.js
> +  let userId = userUuid;
This is the scenario to support astro-cli. If the incoming request do not have userId and only email, so i will need to do a look up and fetch the userId, to inject in code, and since i want to keep the rest of the code the same, i would then need to override userId, which wont be possible since its a const.

PS: this is outdated code. Can you check the file separately.

2020-10-23 16:51 UTC, adam2k commented on src/resolvers/mutation/deployment-update-user-role/index.unit.test.js
> +          userId: userId,
this is a nit: you can change all the `userId: userId,` to `userId,`

2020-10-23 17:58 UTC, adam2k commented
This is a UX improvement that is maybe easy to get in here:

![Screen Shot 2020-10-23 at 1 53 43 PM](https://user-images.githubusercontent.com/749118/97037431-492cf600-1537-11eb-8865-39a511f0c52a.png)

Notice that you'll see `Error: The requested resource was not found` when you try to update a user that isn't added to the workspace yet.  Is it possible to make this error message more clear what's happening?  `This workspace user needs to be added to this deployment.`  Or something like that?

2020-10-23 18:01 UTC, kushalmalani commented
> This is a UX improvement that is maybe easy to get in here:
> 
> ![Screen Shot 2020-10-23 at 1 53 43 PM](https://user-images.githubusercontent.com/749118/97037431-492cf600-1537-11eb-8865-39a511f0c52a.png)
> 
> Notice that you'll see `Error: The requested resource was not found` when you try to update a user that isn't added to the workspace yet. Is it possible to make this error message more clear what's happening? `This workspace user needs to be added to this deployment.` Or something like that?

There should be a case to handle that. Let me check why it is not throwing the right error to you

2020-10-23 18:49 UTC, kushalmalani commented
> This is a UX improvement that is maybe easy to get in here:
> 
> ![Screen Shot 2020-10-23 at 1 53 43 PM](https://user-images.githubusercontent.com/749118/97037431-492cf600-1537-11eb-8865-39a511f0c52a.png)
> 
> Notice that you'll see `Error: The requested resource was not found` when you try to update a user that isn't added to the workspace yet. Is it possible to make this error message more clear what's happening? `This workspace user needs to be added to this deployment.` Or something like that?

(⎈ |gke_astronomer-cloud-dev-236021_us-east4-a_dev-cluster:development)➜  bin ./astro-cli deployment user update kushalmalani@gmail.com --role=DEPLOYMENT_EDITOR --deployment-id=ckghni1280032xpvclen1fih8
Error: This user does not belong to the workspace. Please add the user to the workspace and try again

Can you describe the steps you took? I think you remove the user, but the deployment level role binding still exists

can you create a fresh workspace and try again

ideally that wont happen when we update the remove workspace user mutation to delete all deployment level rolebindings too...thats a TODO

2020-10-23 19:44 UTC, andriisoldatenko requested changes

2020-10-23 19:44 UTC, andriisoldatenko commented on src/schema/mutation.js
> +      nullable: true,
please add `description`

2020-10-23 19:51 UTC, kushalmalani commented on src/schema/mutation.js
> +      nullable: true,
done

2020-10-23 19:59 UTC, adam2k approved these changes
🎉 This looks good to me once that last error message change message change goes in!  Thanks.

2020-10-23 21:07 UTC, adam2k approved these changes
The new error messages look good!  🌮 🎉

2020-10-26 16:30 UTC, andriisoldatenko approved these changes

2020-10-26 18:13 UTC, merged