deployment remove user role
astronomer/houston-api pull request #526
Opened 2020-10-21 23:18 UTC by kushalmalani

## Description

> Describe the purpose of this pull request.
Deployment remove user role

## 🎟 Issue(s)

Resolves astronomer/issues#1762

## 🧪 Functional Testing

> List the functional testing steps to confirm this feature or fix.

## 📸 Screenshots

> Add screenshots to illustrate the validity of these changes.

## 📋 Checklist

- [ ] Rebased from the main (or release if patching) branch (before testing)
- [ ] Ran `yarn lint && yarn test` before taking out of draft
- [ ] Added/updated applicable tests
- [ ] Tested against [Astro-UI](https://github.com/astronomer/astro-ui/) and [Astro-CLI](https://github.com/astronomer/astro-cli/) clients.
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

2020-10-22 22:43 UTC, adam2k commented
I'm logging in as a workspace admin & system admin and trying to delete a viewer user, but I'm getting this error:

```
$ astroDev auth login
Username (leave blank for oAuth):

Please visit the following URL, authenticate and paste token in next prompt

http://localhost:5000/token

oAuth Token: eyJhb....

$ astroDev deployment user delete avandover@gmail.com --deployment-id=ckgjxo7kk0449txc9eixg7xsm
Your Astro CLI Version (0.21.0) is ahead of the server version (0.20.0).
Consider downgrading your Astro CLI to match. See https://www.astronomer.io/docs/cli-quickstart for more information.
Insufficient permissions.
Error: Insufficient permissions.
```

In Houston API the logs only show:

```
2020-10-22T18:41:06 ERROR Insufficient permissions.
```


![Screen Shot 2020-10-22 at 6 43 25 PM](https://user-images.githubusercontent.com/749118/96937599-80979600-1496-11eb-9667-0cfc7ae608de.png)

2020-10-23 14:56 UTC, adam2k requested changes
There is the permissions suggestion that needs to go in for this PR to work correctly.  The other comments are mostly nits.

I would suggest getting that `deployment-add-user-role` code into a different PR though because we'll be able to merge that fast and address the changes in `Astro CLI` for the code that's already merged in since it is a breaking change there.

2020-10-23 14:56 UTC, adam2k commented on src/schema/permissions.js
> +        hasRBAC("system.deployments.update")
This is the bug that's preventing access to run this mutation for any users:

```Suggestion
        or(
            hasRBAC("deployment.userRoles.update"),
            hasRBAC("system.deployments.update")
        )
```

2020-10-23 14:56 UTC, adam2k commented on src/resolvers/mutation/deployment-add-user-role/index.unit.test.js
> +    $userId: Id,
You can leave this in this PR, but do you mind adding these changes to another PR so we can merge them in faster and then I can update the `Astro CLI` code that this affects?

2020-10-23 14:56 UTC, adam2k commented on src/resolvers/mutation/deployment-add-user-role/index.unit.test.js
> +  let email, createRoleBindingId, workspaceId, userId, deploymentId;
🥳 Thanks for changing to `Id`!

2020-10-23 15:11 UTC, kushalmalani commented on src/resolvers/mutation/deployment-add-user-role/index.unit.test.js
> +    $userId: Id,
Its already in the other PR. I rebased this branch of that, so it has latest changes.

2020-10-23 15:13 UTC, kushalmalani commented on src/schema/permissions.js
> +        hasRBAC("system.deployments.update")
Yes, I will have to merge them in order, because i will need to resolve conflicts since they all touch the same files.

2020-10-23 15:27 UTC, andriisoldatenko commented on src/schema/mutation.js
> +      nullable: true,
```suggestion
      nullable: true,
      description : `Some useful text.`,
```

2020-10-23 15:27 UTC, andriisoldatenko commented on src/schema/mutation.js
> +        userId: arg({ type: "Id" }),
pls add `description`

2020-10-23 15:28 UTC, andriisoldatenko commented on src/schema/types.js
> +const Id = scalarType({
do you think we need this?

2020-10-23 15:40 UTC, kushalmalani commented on src/schema/types.js
> +const Id = scalarType({
Yes, houston throws a `Missing type Id, did you forget to import a type to the root query or mean ID, Uuid?` if we dont define that

2020-10-23 16:03 UTC, adam2k commented on src/schema/permissions.js
> +        hasRBAC("system.deployments.update")
If you merge and fix conflicts this bug will still be here, right?

2020-10-23 16:08 UTC, adam2k commented on src/resolvers/mutation/deployment-add-user-role/index.unit.test.js
> +    $userId: Id,
What I mean is this mutation is already merged into master and this PR shouldn't conflate the changes for `deploymentAddUserRole` https://github.com/astronomer/houston-api/pull/513.  I'm recommending that these changes are a hotfix/patch for the PR that you already have merged into main because the other three that are opened for the remaining work are unreleated to `deplymentAddUserRole` unless I'm missing another PR?

2020-10-23 16:09 UTC, kushalmalani commented on src/schema/permissions.js
> +        hasRBAC("system.deployments.update")
What is the deployment role of the user adam@astronomer.io? I dont see this on graphql.

2020-10-23 16:11 UTC, kushalmalani commented on src/resolvers/mutation/deployment-add-user-role/index.unit.test.js
> +    $userId: Id,
They are not, but all of them are still addressing the same ticket to support deployment level RBAC. I am happy to make similar change in a separate PR, we would just have another PR to review. Trying to move the ball fast, since there is more work to get to, once these PRs go in. Let me know if you still want to keep them separate.

2020-10-23 16:13 UTC, adam2k commented on src/schema/permissions.js
> +        hasRBAC("system.deployments.update")
I'm testing this locally.  The roles are `SYSTEM_ADMIN` and `WORKSPACE_ADMIN`.  This suggestion matches the rules for all of the other mutations that you added.  the `or (...` is only missing from `delete` here.

Both Add and Update Deployment User Roles have the `or` and they don't return the permissions error.  Locally when I add this code everything works as planned too.

2020-10-23 16:18 UTC, adam2k commented on src/resolvers/mutation/deployment-add-user-role/index.unit.test.js
> +    $userId: Id,
The mutation changes for `deploymentAddUserRole` are only here and in the implementation file, right?  

I think this has the potential to make the git history in main murky because these changes are unrelated to delete deployment user.  If we need to cherry-pick or roll back for any reason this PR squashed will impact delete deployment user role and add deployment user role.  

I can help you out if you want because I need to patch this in Astro CLI too.

2020-10-23 16:27 UTC, kushalmalani commented on src/resolvers/mutation/deployment-add-user-role/index.unit.test.js
> +    $userId: Id,
I can add the patch

2020-10-23 16:35 UTC, kushalmalani commented on src/resolvers/mutation/deployment-add-user-role/index.unit.test.js
> +    $userId: Id,
https://github.com/astronomer/houston-api/pull/531

2020-10-23 17:28 UTC, andriisoldatenko requested changes

2020-10-23 17:28 UTC, andriisoldatenko commented on src/resolvers/mutation/deployment-remove-user-role/index.js
> +      id: get(first(roleBindings), "id")
what if `get ` returns null?
cc @adam2k

2020-10-23 17:34 UTC, adam2k commented on src/resolvers/mutation/deployment-remove-user-role/index.js
> +      id: get(first(roleBindings), "id")
if there is no default this won't return anything and the result will be `undefined`.  That would crash javascript, but on line 74 @kushalmalani is checking if roleBindings is empty and if the roleBindings.length is 0.  I think the assumption is that if there is at least one roleBinding then the roleBinding must have an `id`.

2020-10-23 17:39 UTC, kushalmalani commented on src/resolvers/mutation/deployment-remove-user-role/index.js
> +      id: get(first(roleBindings), "id")
Thats accurate

2020-10-23 17:44 UTC, andriisoldatenko commented on src/resolvers/mutation/deployment-remove-user-role/index.js
> +      id: get(first(roleBindings), "id")
ok

2020-10-26 02:50 UTC, kushalmalani commented on src/schema/permissions.js
> +        hasRBAC("system.deployments.update")
@adam2k Should be working now. Can you pull latest on houston and then login via cli with new token and validate it.

2020-10-26 16:58 UTC, kushalmalani commented
Changes merged in https://github.com/astronomer/houston-api/pull/522

2020-10-26 16:58 UTC, closed without merging