Cancel invite should delete all associated role bindings
astronomer/houston-api pull request #556
Opened 2020-11-06 22:03 UTC by kushalmalani

## Description

> Describe the purpose of this pull request.
Cancel invite should delete all associated role bindings

## 🎟 Issue(s)

Resolves astronomer/issues#2104

## 🧪 Functional Testing

> List the functional testing steps to confirm this feature or fix.

## 📸 Screenshots

> Add screenshots to illustrate the validity of these changes.

## 📋 Checklist

- [ ] Rebased from the main (or release if patching) branch (before testing)
- [ ] Ran `yarn lint && yarn test` before taking out of draft
- [ ] Added/updated applicable tests
- [ ] Tested against [Astro-UI](https://github.com/astronomer/astro-ui/) and [Astro-CLI](https://github.com/astronomer/astro-cli/) clients.
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

2020-11-06 22:18 UTC, adam2k commented on src/resolvers/mutation/delete-invite-token/index.unit.test.js
> +        deleteMany: jest.fn()
Since this is mocking `deleteMany` how can we confirm that this fix is working?  Can we add one more test where you actually add and remove a couple roles in the db?

2020-11-06 23:05 UTC, adam2k commented on src/resolvers/mutation/delete-invite-token/index.unit.test.js
> +        deleteMany: jest.fn()
@kushalmalani if the additional test takes too long, then feel free to drop in a TODO with the link to the seed data issue we already have in the backlog.  We can add the integration test then.

2020-11-07 14:04 UTC, adam2k commented on .circleci/config.yml
> +          DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres?schema=houston%24default"
@kushalmalani this is what we needed to add for Circle CI to pick up the `env(DATABASE_URL)` if you run into it again in the future.

2020-11-07 14:04 UTC, adam2k approved these changes
This LGTM! Thanks for adding those integration tests.  🎉 🌮

2020-11-07 14:20 UTC, adam2k commented on src/resolvers/mutation/delete-invite-token/index.int.test.js
> +    });
Instead of calling prisma here this test should call the function that uses `prisma.roleBinding.deleteMany`

2020-11-07 14:20 UTC, adam2k requested changes
Found one issue in the test.

2020-11-07 16:47 UTC, kushalmalani commented on src/resolvers/mutation/delete-invite-token/index.int.test.js
> +    const email1 = "not-real-email+1@astronomer.io";
Lets use casual.email?

2020-11-07 18:14 UTC, adam2k commented on src/resolvers/mutation/delete-invite-token/index.int.test.js
> +    const email1 = "not-real-email+1@astronomer.io";
yeah, that's probably OK as long as the email doesn't send.

2020-11-07 18:32 UTC, adam2k approved these changes
This is good with me pending the tests passing.  I did functional testing too and it's working well.

2020-11-07 18:44 UTC, merged